-- Private inbox for letters sent from the Mist Maze main menu.
-- Safe to re-run; adds replies without removing existing letters.

begin;

create table if not exists public.developer_letters (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  player_name text
    check (
      player_name is null
      or char_length(player_name) between 1 and 20
    ),
  message text not null
    check (
      char_length(message) between 1 and 2000
    ),
  created_at timestamptz not null default now()
);

create index if not exists developer_letters_created_at_idx
  on public.developer_letters (created_at desc);

create index if not exists developer_letters_user_created_idx
  on public.developer_letters (user_id, created_at desc);

alter table public.developer_letters enable row level security;

revoke all
  on table public.developer_letters
  from public, anon, authenticated;

grant select, insert
  on table public.developer_letters
  to service_role;

grant usage, select
  on sequence public.developer_letters_id_seq
  to service_role;

create table if not exists public.developer_letter_replies (
  id bigint generated by default as identity primary key,
  letter_id bigint not null references public.developer_letters(id) on delete cascade,
  message text not null check (char_length(message) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists developer_letter_replies_letter_created_idx
  on public.developer_letter_replies (letter_id, created_at);

alter table public.developer_letter_replies enable row level security;

revoke all on table public.developer_letter_replies from public, anon, authenticated;
grant select, insert on table public.developer_letter_replies to service_role;
grant usage, select on sequence public.developer_letter_replies_id_seq to service_role;

-- Both tables stay private: /api/developer-letter authenticates the player
-- and filters by user_id for reads; only the dashboard key can create replies.

commit;
