-- supabase/leaderboard-personal-best.sql
-- One row per user + level + mode.
-- Export leaderboard_scores first if you want to keep historical attempts.

begin;

create table if not exists public.leaderboard_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  player_name text not null
    check (char_length(player_name) between 1 and 20),
  level_key text not null
    check (level_key in ('level1', 'level2', 'level3')),
  mode text not null
    check (mode in ('2d', '3d')),
  time_seconds numeric(10, 3) not null
    check (time_seconds > 0 and time_seconds < 21600),
  country_code text
    check (
      country_code is null
      or country_code ~ '^[A-Z]{2}$'
    ),
  created_at timestamptz not null default now()
);

alter table public.leaderboard_scores
  add column if not exists country_code text;

-- Keep only the fastest historical attempt before adding the unique key.
with ranked_scores as (
  select
    id,
    row_number() over (
      partition by user_id, level_key, mode
      order by time_seconds asc, created_at asc, id asc
    ) as position
  from public.leaderboard_scores
)
delete from public.leaderboard_scores as scores
using ranked_scores
where scores.id = ranked_scores.id
  and ranked_scores.position > 1;

create unique index if not exists leaderboard_scores_personal_best_uidx
  on public.leaderboard_scores (user_id, level_key, mode);

create index if not exists leaderboard_scores_fastest_idx
  on public.leaderboard_scores
  (level_key, mode, time_seconds, created_at);

alter table public.leaderboard_scores enable row level security;

revoke all on table public.leaderboard_scores from anon;
revoke insert, update, delete, truncate, references, trigger
  on table public.leaderboard_scores from authenticated;

grant select
  on table public.leaderboard_scores to authenticated;

drop policy if exists "leaderboard_read_all"
  on public.leaderboard_scores;

drop policy if exists "leaderboard_insert_own"
  on public.leaderboard_scores;

create policy "leaderboard_read_all"
  on public.leaderboard_scores
  for select
  to authenticated
  using (true);

create or replace function public.submit_personal_best(
  p_level_key text,
  p_mode text,
  p_time_seconds numeric,
  p_player_name text,
  p_country_code text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  clean_player_name text :=
    left(trim(coalesce(p_player_name, 'Player')), 20);
  clean_country_code text :=
    nullif(upper(trim(coalesce(p_country_code, ''))), '');
  did_save boolean := false;
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  if p_level_key not in ('level1', 'level2', 'level3') then
    raise exception 'Invalid level';
  end if;

  if p_mode not in ('2d', '3d') then
    raise exception 'Invalid mode';
  end if;

  if p_time_seconds is null
     or p_time_seconds <= 0
     or p_time_seconds >= 21600 then
    raise exception 'Invalid completion time';
  end if;

  if clean_player_name = '' then
    clean_player_name := 'Player';
  end if;

  if clean_country_code is not null
     and clean_country_code !~ '^[A-Z]{2}$' then
    clean_country_code := null;
  end if;

  insert into public.leaderboard_scores (
    user_id,
    player_name,
    level_key,
    mode,
    time_seconds,
    country_code,
    created_at
  )
  values (
    current_user_id,
    clean_player_name,
    p_level_key,
    p_mode,
    round(p_time_seconds, 3),
    clean_country_code,
    now()
  )
  on conflict (user_id, level_key, mode)
  do update set
    player_name = excluded.player_name,
    time_seconds = excluded.time_seconds,
    country_code = excluded.country_code,
    created_at = excluded.created_at
  where excluded.time_seconds < leaderboard_scores.time_seconds
  returning true into did_save;

  return coalesce(did_save, false);
end;
$$;

revoke all
  on function public.submit_personal_best(
    text,
    text,
    numeric,
    text,
    text
  )
  from public;

grant execute
  on function public.submit_personal_best(
    text,
    text,
    numeric,
    text,
    text
  )
  to authenticated;

create or replace function public.get_global_leaderboard()
returns table (
  level_key text,
  mode text,
  player_name text,
  country_code text,
  time_seconds numeric,
  created_at timestamptz,
  global_rank bigint,
  is_current_user boolean
)
language sql
security invoker
set search_path = public
as $$
  with ranked as (
    select
      scores.user_id,
      scores.level_key,
      scores.mode,
      scores.player_name,
      scores.country_code,
      scores.time_seconds,
      scores.created_at,
      rank() over (
        partition by scores.level_key, scores.mode
        order by scores.time_seconds asc, scores.created_at asc
      ) as global_rank
    from public.leaderboard_scores as scores
  )
  select
    ranked.level_key,
    ranked.mode,
    ranked.player_name,
    ranked.country_code,
    ranked.time_seconds,
    ranked.created_at,
    ranked.global_rank,
    ranked.user_id = (select auth.uid()) as is_current_user
  from ranked
  where
    ranked.global_rank <= 10
    or ranked.user_id = (select auth.uid())
  order by
    ranked.level_key,
    ranked.mode,
    ranked.global_rank;
$$;

revoke all
  on function public.get_global_leaderboard()
  from public;

grant execute
  on function public.get_global_leaderboard()
  to authenticated;

commit;
