-- Maze Arsenal global leaderboard setup.
-- Run once in Supabase Dashboard -> SQL Editor.
-- Also enable Authentication -> Anonymous Sign-Ins in the Supabase dashboard.

create table if not exists public.leaderboard_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  player_name text not null
    check (char_length(player_name) between 1 and 20),
  level_key text not null
    check (level_key in ('level1', 'level2', 'level3')),
  mode text not null
    check (mode in ('2d', '3d')),
  time_seconds numeric(10, 3) not null
    check (time_seconds > 0 and time_seconds < 21600),
  country_code text
    check (country_code is null or country_code ~ '^[A-Z]{2}$'),
  created_at timestamptz not null default now()
);

alter table public.leaderboard_scores
  add column if not exists country_code text;

alter table public.leaderboard_scores
  drop constraint if exists leaderboard_scores_country_code_check;

alter table public.leaderboard_scores
  add constraint leaderboard_scores_country_code_check
  check (
    country_code is null
    or country_code ~ '^[A-Z]{2}$'
  );

create index if not exists leaderboard_scores_fastest_idx
  on public.leaderboard_scores
  (level_key, mode, time_seconds, created_at);

create index if not exists leaderboard_scores_user_best_idx
  on public.leaderboard_scores
  (user_id, level_key, mode, time_seconds, created_at);

alter table public.leaderboard_scores enable row level security;

revoke all on table public.leaderboard_scores from anon;
revoke update, delete, truncate, references, trigger
  on table public.leaderboard_scores from authenticated;

grant select, insert
  on table public.leaderboard_scores to authenticated;

drop policy if exists "leaderboard_read_all"
  on public.leaderboard_scores;

create policy "leaderboard_read_all"
  on public.leaderboard_scores
  for select
  to authenticated
  using (true);

drop policy if exists "leaderboard_insert_own"
  on public.leaderboard_scores;

create policy "leaderboard_insert_own"
  on public.leaderboard_scores
  for insert
  to authenticated
  with check (user_id = (select auth.uid()));

create or replace function public.get_global_leaderboard()
returns table (
  level_key text,
  mode text,
  player_name text,
  country_code text,
  time_seconds numeric,
  created_at timestamptz,
  global_rank bigint,
  is_current_user boolean
)
language sql
security invoker
set search_path = public
as $$
  with personal_best as (
    select distinct on (scores.user_id, scores.level_key, scores.mode)
      scores.user_id,
      scores.level_key,
      scores.mode,
      scores.player_name,
      scores.country_code,
      scores.time_seconds,
      scores.created_at
    from public.leaderboard_scores as scores
    order by
      scores.user_id,
      scores.level_key,
      scores.mode,
      scores.time_seconds asc,
      scores.created_at asc
  ),
  ranked as (
    select
      best.user_id,
      best.level_key,
      best.mode,
      best.player_name,
      best.country_code,
      best.time_seconds,
      best.created_at,
      rank() over (
        partition by best.level_key, best.mode
        order by best.time_seconds asc, best.created_at asc
      ) as global_rank
    from personal_best as best
  )
  select
    ranked.level_key,
    ranked.mode,
    ranked.player_name,
    ranked.country_code,
    ranked.time_seconds,
    ranked.created_at,
    ranked.global_rank,
    ranked.user_id = (select auth.uid()) as is_current_user
  from ranked
  where
    ranked.global_rank <= 10
    or ranked.user_id = (select auth.uid())
  order by
    ranked.level_key,
    ranked.mode,
    ranked.global_rank;
$$;

revoke all
  on function public.get_global_leaderboard()
  from public;

grant execute
  on function public.get_global_leaderboard()
  to authenticated;
