-- supabase/setup.sql
-- Mist Maze secure leaderboard and private developer analytics.
-- Safe to re-run. Enable Authentication -> Anonymous Sign-Ins first.

create table if not exists public.leaderboard_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  player_name text not null
    check (char_length(player_name) between 1 and 20),
  level_key text not null
    check (level_key in ('level1', 'level2', 'level3')),
  mode text not null
    check (mode in ('2d', '3d')),
  time_seconds numeric(10, 3) not null
    check (time_seconds > 0 and time_seconds < 21600),
  country_code text
    check (country_code is null or country_code ~ '^[A-Z]{2}$'),
  created_at timestamptz not null default now()
);

alter table public.leaderboard_scores
  add column if not exists country_code text;

alter table public.leaderboard_scores
  drop constraint if exists leaderboard_scores_country_code_check;

alter table public.leaderboard_scores
  add constraint leaderboard_scores_country_code_check
  check (
    country_code is null
    or country_code ~ '^[A-Z]{2}$'
  );

with ranked_scores as (
  select
    id,
    row_number() over (
      partition by user_id, level_key, mode
      order by time_seconds asc, created_at asc, id asc
    ) as row_number
  from public.leaderboard_scores
)
delete from public.leaderboard_scores
where id in (
  select id
  from ranked_scores
  where row_number > 1
);

drop index if exists public.leaderboard_scores_user_best_idx;

create unique index if not exists leaderboard_scores_personal_best_uidx
  on public.leaderboard_scores (user_id, level_key, mode);

create index if not exists leaderboard_scores_fastest_idx
  on public.leaderboard_scores
  (level_key, mode, time_seconds, created_at);

alter table public.leaderboard_scores enable row level security;

revoke all on table public.leaderboard_scores from anon;
revoke all on table public.leaderboard_scores from authenticated;

drop policy if exists "leaderboard_read_all"
  on public.leaderboard_scores;
drop policy if exists "leaderboard_insert_own"
  on public.leaderboard_scores;

create table if not exists public.leaderboard_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  level_key text not null
    check (level_key in ('level1', 'level2', 'level3')),
  mode text not null
    check (mode in ('2d', '3d')),
  started_at timestamptz not null default clock_timestamp()
);

create index if not exists leaderboard_runs_user_idx
  on public.leaderboard_runs (user_id, started_at);

alter table public.leaderboard_runs enable row level security;

revoke all on table public.leaderboard_runs from anon;
revoke all on table public.leaderboard_runs from authenticated;

create or replace function public.start_leaderboard_run(
  p_level_key text,
  p_mode text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  new_run_id uuid;
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  if p_level_key not in ('level1', 'level2', 'level3') then
    raise exception 'Invalid level';
  end if;

  if p_mode not in ('2d', '3d') then
    raise exception 'Invalid mode';
  end if;

  delete from public.leaderboard_runs
  where user_id = current_user_id;

  insert into public.leaderboard_runs (
    user_id,
    level_key,
    mode
  )
  values (
    current_user_id,
    p_level_key,
    p_mode
  )
  returning id into new_run_id;

  return new_run_id;
end;
$$;

revoke all
  on function public.start_leaderboard_run(text, text)
  from public, anon;
grant execute
  on function public.start_leaderboard_run(text, text)
  to authenticated;

create or replace function public.finish_leaderboard_run(
  p_run_id uuid,
  p_player_name text,
  p_country_code text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  run_record public.leaderboard_runs%rowtype;
  clean_name text := nullif(
    left(trim(coalesce(p_player_name, '')), 20),
    ''
  );
  clean_country text := nullif(upper(trim(coalesce(p_country_code, ''))), '');
  elapsed_seconds numeric;
  rounded_seconds numeric(10, 3);
  minimum_seconds numeric;
  affected_rows integer := 0;
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  delete from public.leaderboard_runs
  where id = p_run_id
    and user_id = current_user_id
  returning * into run_record;

  if not found then
    raise exception 'Leaderboard run is missing or already finished';
  end if;

  elapsed_seconds := extract(
    epoch from (clock_timestamp() - run_record.started_at)
  );

  minimum_seconds := case run_record.level_key
    when 'level1' then 2
    when 'level2' then 3
    when 'level3' then 4
    else 2
  end;

  if elapsed_seconds < minimum_seconds
     or elapsed_seconds >= 21600 then
    raise exception 'Leaderboard run duration is invalid';
  end if;

  rounded_seconds := round(elapsed_seconds, 3);

  if clean_country is not null and clean_country !~ '^[A-Z]{2}$' then
    clean_country := null;
  end if;

  insert into public.leaderboard_scores (
    user_id,
    player_name,
    level_key,
    mode,
    time_seconds,
    country_code,
    created_at
  )
  values (
    current_user_id,
    coalesce(clean_name, 'You'),
    run_record.level_key,
    run_record.mode,
    rounded_seconds,
    clean_country,
    clock_timestamp()
  )
  on conflict (user_id, level_key, mode)
  do update set
    player_name = excluded.player_name,
    time_seconds = excluded.time_seconds,
    country_code = excluded.country_code,
    created_at = excluded.created_at
  where excluded.time_seconds < public.leaderboard_scores.time_seconds;

  get diagnostics affected_rows = row_count;

  return jsonb_build_object(
    'improved',
    affected_rows > 0,
    'timeSeconds',
    rounded_seconds
  );
end;
$$;

revoke all
  on function public.finish_leaderboard_run(uuid, text, text)
  from public, anon;
grant execute
  on function public.finish_leaderboard_run(uuid, text, text)
  to authenticated;

create or replace function public.get_global_leaderboard()
returns table (
  level_key text,
  mode text,
  player_name text,
  country_code text,
  time_seconds numeric,
  created_at timestamptz,
  global_rank bigint,
  is_current_user boolean
)
language sql
security definer
set search_path = public
as $$
  with ranked as (
    select
      scores.user_id,
      scores.level_key,
      scores.mode,
      scores.player_name,
      scores.country_code,
      scores.time_seconds,
      scores.created_at,
      rank() over (
        partition by scores.level_key, scores.mode
        order by scores.time_seconds asc, scores.created_at asc
      ) as global_rank
    from public.leaderboard_scores as scores
  )
  select
    ranked.level_key,
    ranked.mode,
    ranked.player_name,
    ranked.country_code,
    ranked.time_seconds,
    ranked.created_at,
    ranked.global_rank,
    ranked.user_id = (select auth.uid()) as is_current_user
  from ranked
  where
    ranked.global_rank <= 10
    or ranked.user_id = (select auth.uid())
  order by
    ranked.level_key,
    ranked.mode,
    ranked.global_rank;
$$;

revoke all
  on function public.get_global_leaderboard()
  from public, anon;
grant execute
  on function public.get_global_leaderboard()
  to authenticated;

create table if not exists public.developer_usage_stats (
  user_id uuid primary key references auth.users(id) on delete cascade,
  last_player_name text
    check (
      last_player_name is null
      or char_length(last_player_name) between 1 and 20
    ),
  games_started bigint not null default 0
    check (games_started >= 0),
  games_finished bigint not null default 0
    check (games_finished >= 0),
  seconds_played bigint not null default 0
    check (seconds_played >= 0),
  donation_1_attempts bigint not null default 0
    check (donation_1_attempts >= 0),
  donation_2_attempts bigint not null default 0
    check (donation_2_attempts >= 0),
  donation_5_attempts bigint not null default 0
    check (donation_5_attempts >= 0),
  donation_custom_attempts bigint not null default 0
    check (donation_custom_attempts >= 0),
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

alter table public.developer_usage_stats
  add column if not exists active_run_started_at timestamptz;
alter table public.developer_usage_stats
  add column if not exists last_playtime_at timestamptz;
alter table public.developer_usage_stats
  add column if not exists last_game_start_at timestamptz;
alter table public.developer_usage_stats
  add column if not exists last_donation_at timestamptz;

alter table public.developer_usage_stats enable row level security;

revoke all on table public.developer_usage_stats from anon;
revoke all on table public.developer_usage_stats from authenticated;
grant select on table public.developer_usage_stats to service_role;

drop function if exists public.record_developer_usage(
  text,
  text,
  integer,
  text
);

create or replace function public.record_developer_usage_server(
  p_user_id uuid,
  p_event text,
  p_donation_key text default null,
  p_seconds integer default 0,
  p_player_name text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_time timestamptz := clock_timestamp();
  clean_name text := nullif(
    left(trim(coalesce(p_player_name, '')), 20),
    ''
  );
  safe_seconds integer := greatest(
    0,
    least(coalesce(p_seconds, 0), 120)
  );
  wall_seconds integer := 0;
  credited_seconds integer := 0;
  stats public.developer_usage_stats%rowtype;
begin
  if p_user_id is null then
    raise exception 'User id is required';
  end if;

  if p_event is null
     or p_event not in (
       'visitor',
       'game_start',
       'game_finish',
       'playtime',
       'donation'
     ) then
    raise exception 'Invalid analytics event';
  end if;

  if p_event = 'donation'
     and (
       p_donation_key is null
       or p_donation_key not in ('1', '2', '5', 'custom')
     ) then
    raise exception 'Invalid donation key';
  end if;

  insert into public.developer_usage_stats (
    user_id,
    last_player_name,
    last_seen_at
  )
  values (
    p_user_id,
    clean_name,
    current_time
  )
  on conflict (user_id) do nothing;

  select *
  into stats
  from public.developer_usage_stats
  where user_id = p_user_id
  for update;

  if stats.active_run_started_at is not null then
    wall_seconds := greatest(
      0,
      floor(
        extract(
          epoch from (
            current_time
            - coalesce(stats.last_playtime_at, stats.active_run_started_at)
          )
        )
      )::integer
    );
  end if;

  if p_event = 'visitor' then
    update public.developer_usage_stats
    set
      last_player_name = coalesce(clean_name, last_player_name),
      last_seen_at = current_time
    where user_id = p_user_id;
    return;
  end if;

  if p_event = 'game_start' then
    if stats.last_game_start_at is null
       or current_time - stats.last_game_start_at >= interval '2 seconds' then
      credited_seconds := least(wall_seconds, 120);

      update public.developer_usage_stats
      set
        last_player_name = coalesce(clean_name, last_player_name),
        games_started = games_started + 1,
        seconds_played = seconds_played + credited_seconds,
        active_run_started_at = current_time,
        last_playtime_at = current_time,
        last_game_start_at = current_time,
        last_seen_at = current_time
      where user_id = p_user_id;
    else
      update public.developer_usage_stats
      set
        last_player_name = coalesce(clean_name, last_player_name),
        last_seen_at = current_time
      where user_id = p_user_id;
    end if;
    return;
  end if;

  if p_event = 'playtime' then
    if stats.active_run_started_at is not null then
      credited_seconds := least(safe_seconds, wall_seconds, 120);
      update public.developer_usage_stats
      set
        last_player_name = coalesce(clean_name, last_player_name),
        seconds_played = seconds_played + credited_seconds,
        last_playtime_at = current_time,
        last_seen_at = current_time
      where user_id = p_user_id;
    end if;
    return;
  end if;

  if p_event = 'game_finish' then
    if stats.active_run_started_at is not null
       and current_time - stats.active_run_started_at >= interval '1 second' then
      credited_seconds := least(
        greatest(safe_seconds, 0),
        wall_seconds,
        120
      );

      update public.developer_usage_stats
      set
        last_player_name = coalesce(clean_name, last_player_name),
        games_finished = games_finished + 1,
        seconds_played = seconds_played + credited_seconds,
        active_run_started_at = null,
        last_playtime_at = null,
        last_seen_at = current_time
      where user_id = p_user_id;
    end if;
    return;
  end if;

  if p_event = 'donation' then
    if stats.last_donation_at is null
       or current_time - stats.last_donation_at >= interval '2 seconds' then
      update public.developer_usage_stats
      set
        donation_1_attempts = donation_1_attempts
          + case when p_donation_key = '1' then 1 else 0 end,
        donation_2_attempts = donation_2_attempts
          + case when p_donation_key = '2' then 1 else 0 end,
        donation_5_attempts = donation_5_attempts
          + case when p_donation_key = '5' then 1 else 0 end,
        donation_custom_attempts = donation_custom_attempts
          + case when p_donation_key = 'custom' then 1 else 0 end,
        last_donation_at = current_time,
        last_seen_at = current_time
      where user_id = p_user_id;
    else
      update public.developer_usage_stats
      set last_seen_at = current_time
      where user_id = p_user_id;
    end if;
  end if;
end;
$$;

revoke all
  on function public.record_developer_usage_server(
    uuid,
    text,
    text,
    integer,
    text
  )
  from public, anon, authenticated;
grant execute
  on function public.record_developer_usage_server(
    uuid,
    text,
    text,
    integer,
    text
  )
  to service_role;
